# Redis Sentinel 3 配置
port 26379

sentinel monitor redis-master-1 redis-node-1 6371 2
sentinel monitor redis-master-2 redis-node-2 6372 2
sentinel monitor redis-master-3 redis-node-3 6373 2

sentinel down-after-milliseconds redis-master-1 5000
sentinel down-after-milliseconds redis-master-2 5000
sentinel down-after-milliseconds redis-master-3 5000

sentinel failover-timeout redis-master-1 10000
sentinel failover-timeout redis-master-2 10000
sentinel failover-timeout redis-master-3 10000

sentinel parallel-syncs redis-master-1 1
sentinel parallel-syncs redis-master-2 1
sentinel parallel-syncs redis-master-3 1

loglevel notice
dir /data
