worker_processes auto;
events { worker_connections 512; }
http {
    upstream backend {
        server ucs-telemetry-store-1:8082;
        server ucs-telemetry-store-2:8082;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
