worker_processes auto;
events { worker_connections 512; }
http {
    upstream backend {
        server ucs-command-1:8084;
        server ucs-command-2:8084;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
