-- =====================================================
-- UCS H2 Init Data Backup Script
-- This SQL mirrors DataInitService.java initialization
-- For reference/backup only; DataInitService handles actual init
-- =====================================================

-- Roles
INSERT INTO role (role_name, description) VALUES
('operator', '队员 - 普通飞手，可查看和控制自己的无人机'),
('leader', '队长 - 可管理队员和分配任务'),
('observer', '观察员 - 全局只读权限，用于大屏展示'),
('commander', '指挥员 - 最高权限，可创建队伍和分配资源');

-- Teams (2 teams: 巡检队伍, 应急队伍)
INSERT INTO team (team_name, description, created_by) VALUES
('巡检队伍', '负责河道、管线等基础设施巡检', 1),
('应急队伍', '负责紧急救援和应急响应任务', 1);

-- Team Roles
INSERT INTO team_role (team_id, role_name, description) VALUES
(1, 'Leader', '队长'),
(1, 'Pilot', '飞手'),
(2, 'Leader', '队长'),
(2, 'Pilot', '飞手');

-- Users (8 total)
-- Partition naming: observer/commander fixed, others user_{id}
-- Password: 123456 (BCrypt encoded)
-- Note: actual password hash is generated by PasswordEncoder at runtime
INSERT INTO users (username, password_hash, real_name, pilot_license_id, phone, email, team_id, partition_name, status) VALUES
('commander',  '$2a$10$placeholder', '指挥官', 'AOPA-COMMANDER', '13800000001', 'commander@ucs.com', NULL, 'commander', 1),
('zhangsan',   '$2a$10$placeholder', '张三',   'AOPA-ZHANGSAN',  '13800000002', 'zhangsan@ucs.com',  1,    'user_2',    1),
('lisi',       '$2a$10$placeholder', '李四',   'AOPA-LISI',      '13800000003', 'lisi@ucs.com',      1,    'user_3',    1),
('wangwu',     '$2a$10$placeholder', '王五',   'AOPA-WANGWU',    '13800000004', 'wangwu@ucs.com',    1,    'user_4',    1),
('zhaoliu',    '$2a$10$placeholder', '赵六',   'AOPA-ZHAOLIU',   '13800000005', 'zhaoliu@ucs.com',   2,    'user_5',    1),
('qianqi',     '$2a$10$placeholder', '钱七',   'AOPA-QIANQI',    '13800000006', 'qianqi@ucs.com',    2,    'user_6',    1),
('sunba',      '$2a$10$placeholder', '孙八',   'AOPA-SUNBA',     '13800000007', 'sunba@ucs.com',     2,    'user_7',    1),
('observer',   '$2a$10$placeholder', '观察员', 'AOPA-OBSERVER',  '13800000008', 'observer@ucs.com',  NULL, 'observer',  1);

-- User-Role mappings
-- (IDs depend on auto-generation order: commander=1, zhangsan=2, ..., observer=8)
-- Role IDs: operator=1, leader=2, observer=3, commander=4
INSERT INTO user_role_map (user_id, role_id) VALUES
(1, 4),  -- commander -> commander role
(2, 2),  -- zhangsan -> leader role
(3, 1),  -- lisi -> operator role
(4, 1),  -- wangwu -> operator role
(5, 2),  -- zhaoliu -> leader role
(6, 1),  -- qianqi -> operator role
(7, 1),  -- sunba -> operator role
(8, 3);  -- observer -> observer role

-- Team Members
INSERT INTO team_member (team_id, user_id, team_role_id) VALUES
(1, 2, 1),  -- zhangsan -> 巡检队伍 Leader
(1, 3, 2),  -- lisi -> 巡检队伍 Pilot
(1, 4, 2),  -- wangwu -> 巡检队伍 Pilot
(2, 5, 3),  -- zhaoliu -> 应急队伍 Leader
(2, 6, 4),  -- qianqi -> 应急队伍 Pilot
(2, 7, 4);  -- sunba -> 应急队伍 Pilot

-- Drones (4 PX4 simulated drones with DDS identifiers)
INSERT INTO drone (drone_sn, uav_id, model, manufacturer, default_team_id, mavlink_system_id, online_status, capabilities) VALUES
('PX4-SIM-001', 'px4_1', 'PX4-SITL', 'PX4', 1, 1, FALSE, '{"camera": true, "thermal": true, "zoom": true}'),
('PX4-SIM-002', 'px4_2', 'PX4-SITL', 'PX4', 1, 2, FALSE, '{"camera": true, "thermal": true, "zoom": true}'),
('PX4-SIM-003', 'px4_3', 'PX4-SITL', 'PX4', 1, 3, FALSE, '{"camera": true, "thermal": false, "zoom": true}'),
('PX4-SIM-004', 'px4_4', 'PX4-SITL', 'PX4', 2, 4, FALSE, '{"camera": true, "thermal": false, "zoom": true}');

-- Drone-Team mappings
INSERT INTO team_drone_map (team_id, drone_id) VALUES
(1, 1),  -- px4_1 -> 巡检队伍
(1, 2),  -- px4_2 -> 巡检队伍
(1, 3),  -- px4_3 -> 巡检队伍
(2, 4);  -- px4_4 -> 应急队伍

-- Drone Ownership
INSERT INTO drone_ownership (drone_id, user_id, assigned_by) VALUES
(1, 3, 1),  -- px4_1 -> lisi, assigned by commander
(2, 3, 1),  -- px4_2 -> lisi
(3, 4, 1),  -- px4_3 -> wangwu
(4, 6, 1);  -- px4_4 -> qianqi

-- Drone Partition Mappings
-- Each drone: observer + commander + owner partition + team leader partition
INSERT INTO drone_partition_map (drone_id, uav_id, partition_name, is_active) VALUES
-- px4_1: observer, commander, user_3(lisi), user_2(zhangsan/leader)
(1, 'px4_1', 'observer',  TRUE),
(1, 'px4_1', 'commander', TRUE),
(1, 'px4_1', 'user_3',    TRUE),
(1, 'px4_1', 'user_2',    TRUE),
-- px4_2: observer, commander, user_3(lisi), user_2(zhangsan/leader)
(2, 'px4_2', 'observer',  TRUE),
(2, 'px4_2', 'commander', TRUE),
(2, 'px4_2', 'user_3',    TRUE),
(2, 'px4_2', 'user_2',    TRUE),
-- px4_3: observer, commander, user_4(wangwu), user_2(zhangsan/leader)
(3, 'px4_3', 'observer',  TRUE),
(3, 'px4_3', 'commander', TRUE),
(3, 'px4_3', 'user_4',    TRUE),
(3, 'px4_3', 'user_2',    TRUE),
-- px4_4: observer, commander, user_6(qianqi), user_5(zhaoliu/leader)
(4, 'px4_4', 'observer',  TRUE),
(4, 'px4_4', 'commander', TRUE),
(4, 'px4_4', 'user_6',    TRUE),
(4, 'px4_4', 'user_5',    TRUE);
